### ISSUE TITLE
Code Formatting On Save

### ISSUE THREAD

**Issue by lalitmee** [Remchi/bookworm-react#10]
Hey, I am interested in knowing that what plugin you were using in the videos of this project. I was seeing the videos and I noticed that all the code was being automatically formatted on save whether it is HTML, js or jsx. 

You pronounced the name but I am not getting clearly. I searched for it but no luck.
**Please tell me. Thanx.**

**Comment by devstojko** [comment]
For VS Code it is Prettier. 
[https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode](url)

**Comment by lalitmee** [comment]
Yeah for VS Code, it is but I saw @Remchi  using something incredible in **sublime**.

**Comment by devstojko** [comment]
Seems like JsFormat for Sublime.
https://packagecontrol.io/packages/JsFormat

**Comment by Remchi** [comment]
Hey guys. I use prettier for all my editors (VSCode, Sublime, Atom and Vim).

**Comment by lalitmee** [comment]
Hey @Remchi, actually I am talking about this change which is happening while in saving file. You have a look at this gif of one of your video. You created an input with lots of fields and when you hit save it changes on its own. Actually I installed jsPrettier in sublime and VS Code both but its not happening.

**Is there any configuration for this step. If yes please tell me if you don't mind. Thanx**
![save](https://user-images.githubusercontent.com/10762218/35737893-1bee1168-0853-11e8-9341-da7deeb2af0d.gif)

**Comment by devstojko** [comment]
Check out this [post](https://scottsauber.com/2017/06/10/prettier-format-on-save-never-worry-about-formatting-javascript-again/) and this [Prettier Setup section](https://hackernoon.com/configure-eslint-prettier-and-flow-in-vs-code-for-react-development-c9d95db07213)

**Comment by lalitmee** [comment]
@djstojadin Thanx for sharing.
