### ISSUE TITLE
Cannot read property 'global' of undefined

### ISSUE THREAD

**Issue by soundariyaa** [Remchi/bookworm-react#17]
Hi ,
In server side middleware routing call is not working. It works well without routing. I am using express 4.16.4, node 10.15.2. 

![image](https://user-images.githubusercontent.com/48952660/55005069-a9665980-4fdb-11e9-9b7e-78aebd25dc13.png)

index.js
import express from "express";
import path from "path";
import mongoose from "mongoose";
import bodyParser from "body-parser";
import auth from "./routes/auth";

const app = express();
// app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
mongoose.connect("mongodb://localhost/bookworm", { useNewUrlParser: true });

console.log("post request");
app.use("api/auth", auth);

// app.post("/api/auth", (req, res) => {
// res.status(400).json({ errors: { global: "Invalid Credentials" } });
// });

app.get("/*", (req, res) => {
  res.sendFile(path.join(__dirname, "index.html"));
});

app.listen(8080, () => console.log("Running on localhost:8080"));

auth.js

import express from "express";
import User from "../models/User";

const router = express.Router();

router.route("/").post((req, res) => {
  const { credentials } = req.body;
  console.log(req.body);
  User.findOne({ email: credentials.email }).then(user => {
    if (user) {
      res.json({ success: true });
    } else {
      res.status(400).json({ errors: { global: "Invalid Credentials" } });
    }
  });
});
export default router;

**Comment by devmeireles** [comment]
any solution?

**Comment by soundariyaa** [comment]
No, I did not find any solution.Still living with the same issue. Not able to route the post in api.

**Comment by soundariyaa** [comment]
I fixed this issue. I forgot to put  / slash in the begining. Now it works perfect.

  app.use("/api/auth", auth);
